[www]
; Escuchar en todas las interfaces para permitir conexiones de nginx
listen = 0.0.0.0:9000

; Permitir que las variables de entorno pasen a PHP-FPM
clear_env = no

; Pasar variables de entorno especificas de la base de datos
env[DB_HOST] = $DB_HOST
env[DB_PORT] = $DB_PORT
env[DB_USER] = $DB_USER
env[DB_PASSWORD] = $DB_PASSWORD
env[DB_NAME] = $DB_NAME
